### ISSUE TITLE
 Coding and Testing Philosophy

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#37] opened 2023-10-06 18:21 UTC
Describe or provide links to your coding standards and testing philosophy that will be used for this product.

**Comment by Cade5480** [comment] 2023-10-10 19:25
Coding Standards:

1.  Naming Conventions: Guidelines for naming variables, functions, classes, and other entities to ensure clarity and consistency.

2.  Indentation and Formatting: Rules for structuring and formatting code to enhance readability and maintainability.

3.  Comments and Documentation: Guidelines for adding comments and documentation to explain the purpose and functionality of the code.

4.  Error Handling: Best practices for handling errors and exceptions in a consistent manner.

5.  Modularity and Code Organization: Recommendations for organizing code into modules, classes, and functions to improve maintainability.

**Comment by Cade5480** [comment] 2023-10-10 19:26
As for testing philosophy there are multiple i researched, here are some examples.

1.  Test-Driven Development (TDD): In TDD, tests are written before the actual code. Developers first write a failing test and then implement the code to make the test pass. This ensures that the code meets the specified requirements.

2.  Behavior-Driven Development (BDD): BDD focuses on the behavior of the software from the end user's perspective. Tests are written in a natural language format, making them accessible to non-technical stakeholders.

3.  Unit Testing: This philosophy involves testing individual units or components of the software in isolation. Unit tests help ensure that each part of the code functions as intended.

4.  Integration Testing: Integration testing verifies the interactions between different components or systems. It ensures that the integrated modules work together as expected.

5.  Continuous Testing: Continuous testing is integrated into the continuous integration/continuous deployment (CI/CD) pipeline. It involves automated testing at various stages of development, providing rapid feedback to developers.

6.  Exploratory Testing: This involves testers exploring the software without predefined test cases. Testers use their domain knowledge and creativity to discover potential issues.

**Comment by Cade5480** [comment] 2023-10-10 19:27
As for me, Unit, Continuous, and Exploratory Testing would be the most realistic for us. Let me know your inputs on which testing philosophy we should use.

**Comment by Cade5480** [comment] 2023-10-10 20:04
he said push the app out, so it sounds like he is leaning heavily towards Exploratory Testing, pushing the app out and finding issues in the code and exploring for those issues reported by testers so we are gonna go with that philosophy.

**Comment by BeepDroid** [comment] 2023-10-10 20:14
Exploratory testing does sound useful, especially with how you've described it -- amazing job, by the way. I also agree with your input of using unit and continuous testing. Testing our units first would be best for us, THEN moving into continuous/exploratory testing. I feel.

**Comment by Cade5480** [comment] 2023-10-12 16:04
That is actually a great point you made, definitely agree with using unit testing and then move into the continuous/exploratory testing. Thank you Kerry!

**Comment by Cade5480** [comment] 2023-10-12 19:02
Sounds good! It has been submitted and I can close this issue.

**Closed** 2023-10-12 19:48 UTC
Labels: enhancement
